// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaAgY9bqVa1fEDxX8drmgty_hc_OzuLQU',
    appId: '1:456822337245:web:8f01763517bc44556cf534',
    messagingSenderId: '456822337245',
    projectId: 'activity14-b4c20',
    authDomain: 'activity14-b4c20.firebaseapp.com',
    storageBucket: 'activity14-b4c20.firebasestorage.app',
    measurementId: 'G-6HZ9N17G8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS3JG4yvAbT-tFqBAscEp8T-_4dOuG41c',
    appId: '1:456822337245:android:582028af8748364d6cf534',
    messagingSenderId: '456822337245',
    projectId: 'activity14-b4c20',
    storageBucket: 'activity14-b4c20.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaAgY9bqVa1fEDxX8drmgty_hc_OzuLQU',
    appId: '1:456822337245:web:9ae2f27aac1ceeac6cf534',
    messagingSenderId: '456822337245',
    projectId: 'activity14-b4c20',
    authDomain: 'activity14-b4c20.firebaseapp.com',
    storageBucket: 'activity14-b4c20.firebasestorage.app',
    measurementId: 'G-14HHGS2DZY',
  );
}
